In [42]:
import torch
print(torch.__version__)

2.9.0+cu126


In [17]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU")

GPU is available
Using GPU: Tesla T4


In [18]:
# using empty
a = torch.empty(2,3)

In [19]:
#check type
type(a)

torch.Tensor

In [20]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [21]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [22]:
# using rand
torch.rand(2,3)

tensor([[0.4512, 0.7168, 0.9254],
        [0.6644, 0.5010, 0.4795]])

In [23]:
# manual_seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [24]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [25]:
#using tensor
torch.tensor([[1,2,3], [4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [26]:
# arange
print("using arange : ", torch.arange(0,10,2))

using arange :  tensor([0, 2, 4, 6, 8])


In [27]:
# using linspace
print("using linspace: ", torch.linspace(0,10,10))

using linspace:  tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])


In [28]:
# using eye
print("using eye: ", torch.eye(5))

using eye:  tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [29]:
# using full
print("using full: ", torch.full((3,3),5))

using full:  tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


In [ ]:
Tensor Shapes

In [38]:
x = torch.tensor([[1,2,3], [4,5,6]])
print(x)


tensor([[1, 2, 3],
        [4, 5, 6]])


In [39]:
x.shape

torch.Size([2, 3])

In [40]:
torch.empty_like(x)

tensor([[      839094416, 135138572164448,               3],
        [              4,               5,               6]])

In [44]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [45]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [53]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])


Tensor Data Types
```
# This is formatted as code
```



In [47]:
# find data type
x.dtype

torch.int64

In [49]:
# assign data type
torch.tensor([1.0, 2.0, 3.0] , dtype = torch.int32)


tensor([1, 2, 3], dtype=torch.int32)

In [50]:
torch.tensor([1,2,3], dtype = torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [51]:
print(x)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [52]:
# change existing tensor data type
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

**Mathematical Operations**

> 1. Scalar operation



In [56]:
x = torch.rand(2,2)
print(x)

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])


In [57]:
#addition
x + 2

tensor([[2.7118, 2.7876],
        [2.4183, 2.9014]])

In [58]:
# substraction
x - 2

tensor([[-1.2882, -1.2124],
        [-1.5817, -1.0986]])

In [59]:
# multiplication
x * 2

tensor([[1.4235, 1.5752],
        [0.8366, 1.8028]])

In [60]:
# division
x / 3

tensor([[0.2373, 0.2625],
        [0.1394, 0.3005]])

In [61]:
# int division
(x * 100) // 3

tensor([[23., 26.],
        [13., 30.]])

In [62]:
# mod
x % 2

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [63]:
# power
x**2

tensor([[0.5066, 0.6203],
        [0.1750, 0.8125]])

**Element wise operation**

In [65]:
a = torch.rand(2,3)
b = torch.rand(2,3)
print(a)
print(b)

tensor([[0.2426, 0.7003, 0.5277],
        [0.2472, 0.7909, 0.4235]])
tensor([[0.0169, 0.2209, 0.9535],
        [0.7064, 0.1629, 0.8902]])


In [68]:
# add
a + b

# sub
a - b

# multiply
a*b

#division
a / b

#power
a ** b

# mod
a % b


tensor([[0.0060, 0.0377, 0.5277],
        [0.2472, 0.1394, 0.4235]])

In [70]:
c = torch.tensor([1, -2, 3, -4])

In [71]:
# absolute
torch.abs(c)

tensor([1, 2, 3, 4])

In [72]:
#negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [75]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [76]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [77]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [78]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [80]:
# clamp
torch.clamp(d, min = 2, max = 3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

**Reduction Operation**

In [87]:
e = torch.randint(size=(2,3), low=0, high=10, dtype = torch.float32)
print(e)

tensor([[2., 6., 7.],
        [7., 8., 3.]])


In [88]:
# sum
torch.sum(e)

tensor(33.)

In [89]:
# sum along column
torch.sum(e, dim=0)

tensor([ 9., 14., 10.])

In [90]:
# sum along row
torch.sum(e, dim = 1)

tensor([15., 18.])

In [95]:
# mean
torch.mean(e)

# mean along col
torch.mean(e, dim=0)

#mean along row
torch.mean(e, dim=1)


tensor([5., 6.])

In [93]:
# median
torch.median(e)

tensor(6.)

In [97]:
# max and min
torch.max(e)
torch.min(e)

tensor(2.)

In [99]:
# product
torch.prod(e)

tensor(14112.)

In [100]:
# standard deviation
torch.std(e)

tensor(2.4290)

In [101]:
# variance
torch.var(e)

tensor(5.9000)

In [102]:
# argmax
torch.argmax(e)

tensor(4)

In [103]:
# argmin
torch.argmin(e)

tensor(0)

**Matrix Operation**

In [106]:
f = torch.randint(size=(2,3), low = 0, high=10)
g = torch.randint(size=(3,2), low = 0, high=10)
print(f)
print(g)

tensor([[2, 9, 5],
        [0, 4, 2]])
tensor([[7, 1],
        [1, 5],
        [4, 4]])


In [107]:
# matrix multiplication
torch.matmul(f,g)

tensor([[43, 67],
        [12, 28]])

In [108]:
vector1 = torch.tensor([1,2])
vector2 = torch.tensor([3,4])

# dot product
torch.dot(vector1, vector2)



tensor(11)

In [109]:
# transpose
torch.transpose(f, 0, 1)

tensor([[2, 0],
        [9, 4],
        [5, 2]])

In [111]:
h = torch.randint(size=(3,3), low = 0, high = 10, dtype=torch.float32)
print(h)

tensor([[4., 5., 6.],
        [9., 2., 3.],
        [1., 0., 2.]])


In [112]:
# determinant
torch.det(h)

tensor(-71.0000)

In [113]:
torch.inverse(h)

tensor([[-0.0563,  0.1408, -0.0423],
        [ 0.2113, -0.0282, -0.5915],
        [ 0.0282, -0.0704,  0.5211]])

**Comparison Operations**

In [114]:
i = torch.randint(size=(2,3), low = 0, high = 10)
j = torch.randint(size=(2,3), low = 0, high = 10)
print(i)
print(j)

tensor([[1, 2, 7],
        [9, 2, 4]])
tensor([[6, 6, 8],
        [4, 9, 0]])


In [115]:
# greater than
i > j

tensor([[False, False, False],
        [ True, False,  True]])

In [116]:
# less than
i < j

tensor([[ True,  True,  True],
        [False,  True, False]])

In [117]:
# equal to
i == j

tensor([[False, False, False],
        [False, False, False]])

In [118]:
# greater than equal to
i >= j

tensor([[False, False, False],
        [ True, False,  True]])

In [119]:
# less than equal to
i <= j

tensor([[ True,  True,  True],
        [False,  True, False]])

**Special Function**

In [127]:
k = torch.randint(size=(2,3), low = 0, high = 10, dtype=torch.float32)
print(k)

tensor([[5., 1., 0.],
        [0., 2., 2.]])


In [122]:
#log
torch.log(k)

tensor([[1.3863, 1.3863, 1.7918],
        [0.6931, 0.0000,   -inf]])

In [123]:
#exponent
torch.exp(k)

tensor([[ 54.5981,  54.5981, 403.4288],
        [  7.3891,   2.7183,   1.0000]])

In [124]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9820, 0.9820, 0.9975],
        [0.8808, 0.7311, 0.5000]])

In [128]:
#softmax
torch.softmax(k, dim=0)

tensor([[0.9933, 0.2689, 0.1192],
        [0.0067, 0.7311, 0.8808]])

In [129]:
#relu
torch.relu(k)

tensor([[5., 1., 0.],
        [0., 2., 2.]])

**Inplace Operation**

In [130]:
m = torch.rand(2,3)
n = torch.rand(2,3)
print(m)
print(n)

tensor([[0.1132, 0.4783, 0.4436],
        [0.3847, 0.4521, 0.5569]])
tensor([[0.9952, 0.0015, 0.0813],
        [0.4907, 0.2130, 0.4603]])


In [131]:
m+n

tensor([[1.1084, 0.4798, 0.5249],
        [0.8755, 0.6651, 1.0172]])

In [132]:
m.add_(n)

tensor([[1.1084, 0.4798, 0.5249],
        [0.8755, 0.6651, 1.0172]])

In [133]:
m

tensor([[1.1084, 0.4798, 0.5249],
        [0.8755, 0.6651, 1.0172]])

In [134]:
n

tensor([[0.9952, 0.0015, 0.0813],
        [0.4907, 0.2130, 0.4603]])

In [135]:
torch.relu(m)

tensor([[1.1084, 0.4798, 0.5249],
        [0.8755, 0.6651, 1.0172]])

In [136]:
torch.relu_(m)

tensor([[1.1084, 0.4798, 0.5249],
        [0.8755, 0.6651, 1.0172]])

**Copying a Tensor**

In [137]:
a = torch.rand(2,3)
print(a)

tensor([[0.1386, 0.0277, 0.5662],
        [0.3503, 0.6555, 0.7667]])


In [138]:
b = a

In [139]:
b

tensor([[0.1386, 0.0277, 0.5662],
        [0.3503, 0.6555, 0.7667]])

In [140]:
a[0][0] = 5

In [141]:
a

tensor([[5.0000, 0.0277, 0.5662],
        [0.3503, 0.6555, 0.7667]])

In [142]:
b

tensor([[5.0000, 0.0277, 0.5662],
        [0.3503, 0.6555, 0.7667]])

In [143]:
id(a)

135133163628624

In [144]:
id(b)

135133163628624

In [145]:
b = a.clone()

In [146]:
b

tensor([[5.0000, 0.0277, 0.5662],
        [0.3503, 0.6555, 0.7667]])

In [147]:
a

tensor([[5.0000, 0.0277, 0.5662],
        [0.3503, 0.6555, 0.7667]])

In [148]:
a[0][0] = 6

In [149]:
a

tensor([[6.0000, 0.0277, 0.5662],
        [0.3503, 0.6555, 0.7667]])

In [150]:
b

tensor([[5.0000, 0.0277, 0.5662],
        [0.3503, 0.6555, 0.7667]])

In [151]:
id(a)

135133163628624

In [152]:
id(b)

135133758974992

**Tensor Operation on GPU**

In [154]:
torch.cuda.is_available()

True

In [155]:
device = torch.device('cuda')

In [158]:
#creating a new tensor on GPU
torch.rand((2,3), device=device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [162]:
# moving exiating tensor to GPU
d= a.to(device)
print(d)

tensor([[6.0000, 0.0277, 0.5662],
        [0.3503, 0.6555, 0.7667]], device='cuda:0')


In [163]:
b + 5

tensor([[11.0000,  5.0277,  5.5662],
        [ 5.3503,  5.6555,  5.7667]], device='cuda:0')

**Reshaping Tensors**

In [166]:
p = torch.ones(4,4)
print(p)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [168]:
#reshape
p.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [169]:
#flatten
a.flatten()

tensor([6.0000, 0.0277, 0.5662, 0.3503, 0.6555, 0.7667])

In [170]:
q = torch.rand(2,3,4)
print(q)

tensor([[[0.2269, 0.7555, 0.6458, 0.3673],
         [0.1770, 0.2966, 0.9925, 0.2103],
         [0.1292, 0.1719, 0.9127, 0.6818]],

        [[0.1953, 0.9991, 0.1133, 0.0135],
         [0.1450, 0.7819, 0.3134, 0.2983],
         [0.3436, 0.2028, 0.9792, 0.4947]]])


In [173]:
#permute
q.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [177]:
#unsqueeze
# image size
r = torch.rand(226, 226, 3)
r.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [178]:
#squeez
s = torch.rand(1, 20)
d.squeeze(0).shape



torch.Size([2, 3])

**Numpy and PyTorch**

In [179]:
import numpy as np

In [182]:
t = torch.tensor([1,2,3])
print(t)

tensor([1, 2, 3])


In [183]:
u = t.numpy()

In [184]:
print(u)

[1 2 3]


In [186]:
type(u)

numpy.ndarray

In [188]:
v = np.array([2,3,4])
print(v)

[2 3 4]


In [189]:
torch.from_numpy(v)

tensor([2, 3, 4])

In [190]:
type(v)

numpy.ndarray